// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gtfpkmfjtmhpesojleoe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd0ZnBrbWZqdG1ocGVzb2psZW9lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2MTM1MzUsImV4cCI6MjA2MTE4OTUzNX0.F9FafsGiJPmGRWVENMHwAZXWrhvh2lRz1KZtnLJY9YQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);